#!/bin/sh
cd $(dirname $0)

IEXEC_OUT=/tmp/iexec_out

rm -rf $IEXEC_OUT
mkdir -p $IEXEC_OUT

docker run --rm -e IEXEC_OUT=/iexec_out -v $IEXEC_OUT:/iexec_out offchain-python-randomness-uint256

echo
find $IEXEC_OUT
